Football_3TL/Areas/Admin/Controllers/HoaDonController.cs
using Football_3TL.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Football_3TL.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HoaDonController : Controller
    {
        private readonly Football3tlContext _db;

        public HoaDonController(Football3tlContext db)
        {
            _db = db;
        }
       
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DanhSachLichSu()
        {
            var danhSachLichSu = _db.LichSus
                .Include(ls => ls.MaChuSanNavigation)
                .Include(ls => ls.MaGoiNavigation)
                .Select(ls => new
                {
                    MaLichSu = ls.MaLichSu,
                    TenChuSan = ls.MaChuSanNavigation != null ? ls.MaChuSanNavigation.HoVaTen : "Chưa có",
                    TenSan = ls.MaChuSanNavigation != null ? ls.MaChuSanNavigation.TenSanBong : "Chưa có",
                    ThoiHan = ls.MaGoiNavigation != null ? ls.MaGoiNavigation.ThoiHan + " tháng" : "Chưa có",
                    NgayThanhToan = ls.ThoiGian.HasValue ? ls.ThoiGian.Value.ToString("dd/MM/yyyy") : "Chưa có",
                    TongTien = ls.TongThanhToan
                })
                .ToList();

            return Json(danhSachLichSu);
        }
    }
}

Football_3TL/Areas/Admin/Controllers/ThongKeController.cs
using Football_3TL.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Football_3TL.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ThongKeController : Controller
    {
        private readonly Football3tlContext _db;

        public ThongKeController(Football3tlContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ThongKeTongQuan()
        {
            decimal tongDoanhThu = _db.LichSus.Sum(ls => ls.TongThanhToan);
            int soLuongHoaDon = _db.LichSus.Count();
            int tongChuSan = _db.ChuSans.Count();
            int soluongSan = _db.SanBongs.Count();

            return Json(new
            {
                TongDoanhThu = tongDoanhThu,
                SoLuongHoaDon = soLuongHoaDon,
                TongChuSan = tongChuSan,
                SoluongSan = soluongSan
            });
        }
        public IActionResult DoanhThuTheoChuSan()
        {
            var chiTiet = _db.ThongTinDatSans
                .Include(ds => ds.MaChuSanNavigation)
                .Where(ds => ds.NgayDat.HasValue && ds.TrangThaiThanhToan == "Đã thanh toán")
                .Select(ds => new
                {
                    MaChuSan = ds.MaChuSan,
                    TenChuSan = ds.MaChuSanNavigation != null ? ds.MaChuSanNavigation.HoVaTen : "Chưa xác định",
                    TongTien = ds.TongThanhToan
                })
                .ToList();

            var data = chiTiet
                .GroupBy(x => new { x.MaChuSan, x.TenChuSan })
                .Select(g => new
                {
                    TenChuSan = g.Key.TenChuSan,
                    TongTien = g.Sum(x => x.TongTien)
                })
                .OrderByDescending(x => x.TongTien)
                .ToList();

            decimal tongTatCa = chiTiet.Sum(x => x.TongTien);

            return Json(new
            {
                ChiTiet = data,
                TongTatCa = tongTatCa
            });
        }

        public IActionResult DoanhThuTheoThang()
        {
            var lichSu = _db.LichSus
                .Where(ls => ls.ThoiGian.HasValue) // Chỉ lấy bản ghi có thời gian thanh toán
                .Select(ls => new
                {
                    Thang = ls.ThoiGian.Value.Month,
                    TongTien = ls.TongThanhToan
                })
                .ToList();

            var data = lichSu
                .GroupBy(x => x.Thang)
                .Select(g => new
                {
                    Thang = g.Key,
                    TongTien = g.Sum(x => x.TongTien)
                })
                .OrderBy(x => x.Thang)
                .ToList();

            return Json(data);
        }



    }
}

Football_3TL/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản lý</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://cdn.lineicons.com/4.0/lineicons.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <link rel="stylesheet" href="~/css/CssAdmin.css">
</head>

<body>
    <div class="wrapper">
        <div id="sidebar" class="expand">
            <div class="d-flex">
                <button class="toggle-btn" type="button">
                    <i class="lni lni-grid-alt"></i>
                </button>
                <div class="sidebar-logo">
                    <a href="#">3TL FOOTBALL</a>
                </div>
            </div>
            <ul class="sidebar-nav">
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="QuanLyTaiKhoan" asp-action="Index">
                        <i class="lni lni-user"></i>
                        <span>Quản lý tài khoản</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="QuanLyGoi" asp-action="Index">
                        <i class="fas fa-cubes"></i>
                        <span>Quản lý gói</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="HoaDon" asp-action="Index">
                        <i class="lni lni-agenda"></i>
                        <span>Hóa đơn</span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="ThongKe" asp-action="Index">
                        <i class="lni lni-agenda"></i>
                        <span>Thống kê</span>
                    </a>
                </li>
            </ul>
        </div>
        @RenderBody()
    </div>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="~/js/JsAdmin/QuanLyTaiKhoan.js"></script>
    <script src="~/js/JsAdmin/QuanLyGoi.js"></script>
    <script src="~/js/JsAdmin/HoaDon.js"></script>
    <script src="~/js/JsAdmin/ThongKeAdmin.js"></script>
    <script src="https://code.highcharts.com/highcharts.js"></script>
</body>

</html>